batch_size: 64
classes:
- 0
- 1
- 2
flow_epochs: 10
flow_name: flow
lr: 0.001
mask: half
mode: flow
model_dir: models/test
n_images: 5000
n_layers: 2
no_discretise: true
num_hidden: 32
num_members: 10
num_transformations: 2
seed: 21
vae_epochs: 200
vae_name: vae
